discordLink: https://discord.gg/CattoShield
muteMessage: §cYou are currently muted, appeal this mute at https://discord.gg/CattoShield.
banMessage: §cYou are currently banned, appeal this ban at https://discord.gg/CattoShield.