name: Utils
version: '${project.version}'
main: me.frandma.utils.Utils
authors: [ Frandma ]
description: Core plugin.
website: https://cryptostresser.com/
commands:
  ban:
    description: Remove the permission to play.
    permission: utils.ban
    permission-message: §cYou cannot do that.
    usage: §c/ban <player> <reason>
    aliases: [ unban ]
  clear:
    description: Clear inventories.
    permission: utils.clear
    permission-message: §cYou cannot do that.
    usage: §c/clear [player]
    aliases: [ c ]
  discord:
    description: Sends the discord invite.
    usage: §c/discord
    aliases: [ disc ]
  gamemode:
    description: Change gamemode.
    permission: utils.gamemode
    permission-message: §cYou cannot do that.
    usage: §c/gamemode <gamemode> [player]
    aliases: [ gm , gms , gmc , gma , gmsp ]
  give:
    description: Give items to yourself or others.
    permission: utils.give
    permission-message: §cYou cannot do that.
    usage: §c/give [player] <item> [amount]
    aliases: [ item , i ]
  message:
    description: Send private messages.
    usage: §c/message <player> <message>
    aliases: [ msg , w , whisper ]
  mod:
    description: Helpful mod tools.
    permission: utils.mod
    permission-message: §cYou cannot do that.
  mutechat:
    description: Silence all players.
    usage: §c/mutechat
    permission: utils.mutechat
    permission-message: §cYou cannot do that.
  mute:
    description: Silence a player.
    usage: §c/mute <player> <reason>
    aliases: [ unmute ]
    permission: utils.mute
    permission-message: §cYou cannot do that.
  powertool:
    description: Give super powers to items.
    permission: utils.powertool
    permission-message: §cYou cannot do that.
    usage: §c/powertool <chatmessage>
    aliases: [ pt ]
  staffchat:
    description: Talk with other staff.
    permission: utils.staff
    permission-message: §cYou cannot do that.
    usage: §c/staffchat [message]
    aliases: [ sc ]
  sudo:
    description: Make someone chat or do commands.
    permission: utils.sudo
    permission-message: §cYou cannot do that.
    usage: §c/sudo <player> <sudo>
  teleport:
    description: Teleport the specified player.
    permission: utils.teleport
    permission-message: §cYou cannot do that.
    usage: §c/teleport <player> [player]
    aliases: [ tp ]
  tphere:
    description: Teleport a player to yourself.
    permission: utils.teleport
    permission-message: §cYou cannot do that.
    usage: §c/tphere <player>
  vanish:
    description: Become invisible.
    permission: utils.vanish
    permission-message: §cYou cannot do that.
    usage: §c/vanish [player]
    aliases: [ v ]
  view:
    description: View inventories.
    permission: utils.view
    permission-message: §cYou cannot do that.
    usage: §c/view <player>
    aliases: [ invsee , openinv ]